import test from 'node:test';
import assert from 'node:assert/strict';
import { buildContentSnapshot, buildManifest, buildSnapshot, directScriptToVideoScript, distributeMedia, fallbackKnowledgeScript, fallbackScript, normalizeForComparison, similarity, validateScript } from '../src/pipeline.ts';
import { productionOptions, resolveProductionLine } from '../src/presets.ts';
import { extractPageMedia } from '../src/media.ts';

const project={id:'1cc543ff648e',name:'Phone Loops',nameZh:'手机挂绳品牌',revenue:'$1.5M/Year',summary:'用手机挂绳解决单手握持问题。',businessModel:'独立站销售自有品牌产品。',insight:'高频微小需求可以形成品牌。',businessLoop:'内容引流到独立站成交，再通过新品促进复购。',chinaOpportunity:'先针对特定场景做小批量付费验证。',url:'https://example.com/source',image:'https://example.com/a.jpg'};
const article={keyFacts:[{label:'覆盖国家',value:'100+'}],media:[1,2,3,4,5].map((n)=>({type:'image',url:`https://example.com/${n}.jpg`,caption:`素材${n}`})),source:{name:'Source',url:'https://example.com/source'}};

test('buildSnapshot keeps evidence and media',()=>{const snapshot=buildSnapshot(project,article,'2026-07-31T00:00:00Z');assert.equal(snapshot.caseId,project.id);assert.ok(snapshot.facts.length>=5);assert.equal(snapshot.media.length,5)});
test('fallback script passes grounding validation',()=>{const snapshot=buildSnapshot(project,article);const script=fallbackScript(snapshot);const result=validateScript(script,snapshot);assert.equal(result.ok,true,result.errors.join('\n'));assert.equal(script.beats.length,8)});
test('similarity tolerates punctuation',()=>{assert.equal(normalizeForComparison('你好，世界。'),'你好世界');assert.ok(similarity('这是一个真实案例。','这是一个真实案例')>.99)});
test('youtube embeds prefer max-resolution thumbnails over low-resolution posters',()=>{const snapshot=buildSnapshot(project,{...article,media:[{type:'video',url:'https://www.youtube.com/embed/dt24DresEbE',poster:'https://i.ytimg.com/vi/dt24DresEbE/hqdefault.jpg',caption:'产品演示'}]});assert.equal(snapshot.media[0].type,'image');assert.equal(snapshot.media[0].url,'https://i.ytimg.com/vi/dt24DresEbE/maxresdefault.jpg');assert.equal(snapshot.media[0].sourceUrl,'https://www.youtube.com/embed/dt24DresEbE')});
test('official page discovery keeps product images and videos but rejects logos',()=>{const html='<img src="/cdn/shop/files/product.jpg" alt="顾客使用手机挂绳"><img src="/cdn/shop/files/logo.png"><video poster="/cdn/shop/files/demo.jpg"><source src="/cdn/shop/videos/demo.mp4" type="video/mp4"></video>';const media=extractPageMedia(html,'https://shop.example.com/products/sling');assert.deepEqual(media.map(item=>item.type),['image','image','video']);assert.equal(media[0].caption,'顾客使用手机挂绳');assert.ok(media.every(item=>item.sourceUrl.includes('/products/sling')))});
test('official page discovery finds videos embedded in storefront JSON',()=>{const html='<script type="application/json">{"contentUrl":"https:\\/\\/shop.example.com\\/cdn\\/shop\\/videos\\/usage-demo.webm?v=3"}</script>';const media=extractPageMedia(html,'https://shop.example.com/products/sling');assert.equal(media.length,1);assert.equal(media[0].type,'video');assert.match(media[0].url,/usage-demo\.webm/)});
test('media distribution gives every beat a varied visual pool',()=>{const snapshot=buildSnapshot(project,{...article,media:[1,2,3,4,5,6,7,8].map(n=>({type:'image',url:`https://example.com/${n}.jpg`,caption:`素材${n}`}))});const script=distributeMedia(fallbackScript(snapshot),snapshot);assert.ok(script.beats.every(beat=>new Set(beat.mediaIds).size===5));assert.ok(new Set(script.beats.flatMap(beat=>beat.mediaIds)).size>=8)});
test('book text becomes a source-grounded generic snapshot',()=>{const snapshot=buildContentSnapshot({sourceType:'book',title:'思考，快与慢',text:'人类的判断由两套思维系统共同影响。系统一快速直觉，系统二缓慢审慎。理解两者能帮助我们识别判断偏差。'});assert.equal(snapshot.sourceType,'book');assert.equal(snapshot.title,'思考，快与慢');assert.ok(snapshot.facts.length>=2);assert.equal(snapshot.media.length,0)});
test('knowledge preset can render without external media',()=>{const snapshot=buildContentSnapshot({sourceType:'topic',title:'复利',text:'复利不是短期暴涨，而是收益持续进入下一轮增长。时间和稳定投入共同决定长期结果。'});const script=fallbackKnowledgeScript(snapshot);const manifest=buildManifest('job-1',snapshot,script,1,{visualPreset:'knowledge-diagram',aspectRatio:'16:9',durationSeconds:60});assert.equal(manifest.quality.minUniqueMedia,0);assert.equal(manifest.quality.width,1920);assert.equal(manifest.quality.height,1080);assert.equal(manifest.contentSnapshot.title,'复利')});
test('direct script route preserves every spoken character',()=>{const snapshot=buildContentSnapshot({sourceType:'script',title:'家庭与面子',text:'真正的安全感，不是别人眼里的体面。它来自你愿意照顾身边的人，也愿意拒绝无意义的比较。很多人把时间花在证明自己，却忘了生活不是一场表演。稳定的关系来自诚实、边界和长期照顾，而不是短暂的掌声。把日子过好，比把日子演好更重要。'});const script=directScriptToVideoScript(snapshot);assert.equal(script.beats.map(beat=>beat.narration).join(''),snapshot.rawText);assert.equal(validateScript(script,snapshot).ok,true);assert.equal(script.subheadline,'原稿直出 · 不改写口播')});
test('production lines cannot leak visual or brand settings across routes',()=>{const options=productionOptions('script',{productionLineId:'comic-engraving-v1',visualPreset:'real-montage',brandPreset:'ai-shengyi-jing'});assert.equal(options.visualPreset,'comic');assert.equal(options.brandPreset,'comic-engraving');assert.throws(()=>resolveProductionLine('ai-shengyi-case','comic-engraving-v1'),/PRODUCTION_LINE_SOURCE_MISMATCH/)});
test('comic manifest is versioned and requires one generated image per beat',()=>{let snapshot=buildContentSnapshot({sourceType:'script',title:'认知短片',text:'你以为面子能换来尊重，真正稳定的关系，却来自诚实和边界。很多人努力迎合所有人的期待，最后却没有时间照顾自己的生活。先分清什么是责任，什么只是害怕被评价，再决定把时间和精力交给谁。把日子过好，比把日子演好更重要。'});const script=directScriptToVideoScript(snapshot);snapshot={...snapshot,media:script.beats.map((beat,index)=>({id:`comic-${index+1}`,type:'image',url:`https://example.com/comic-${index+1}.jpg`,caption:beat.onScreen,origin:'workers-ai-generated'}))};const withMedia={...script,beats:script.beats.map((beat,index)=>({...beat,mediaIds:[`comic-${index+1}`]}))};const manifest=buildManifest('job-comic',snapshot,withMedia,1,{productionLineId:'comic-engraving-v1'});assert.equal(manifest.template,'comic-engraving-v1');assert.equal(manifest.templateVersion,'1.0.0');assert.equal(manifest.options.visualPreset,'comic');assert.equal(manifest.quality.minUniqueMedia,script.beats.length)});
